{% set name = "rubin-libradtran" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.libradtran.org/download/libRadtran-{{ version }}.tar.gz
  sha256: 3f0bc78f0f930c060fd57dbd33e980280003a2498373eda1be92e9254bdce1a6

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
    - autoconf
    - gnuconfig
    - automake
    - gawk
  host:
    - flex
    - perl
    - libnetcdf
    - netcdf4
    - gsl
    - python
    - libblas
    - libcblas
  run:
    - python
    - openblas
    - netcdf4

test:
  commands:
    - test -f $PREFIX/lib/libRadtran_c.a
    - test -f $PREFIX/lib/libRadtran_f.a
    - test -d $PREFIX/share/libRadtran/data
    - test -f $PREFIX/bin/uvspec
    - uvspec -v

about:
  home: http://libradtran.org
  summary: library for radiative transfer
  description: |
    libradtran (library for radiative transfer) is a collection of C and
    Fortran functions and programs for calculation of solar and thermal
    radiation in the Earth's atmosphere.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - erykoff
